shm_write:shm_write.c
	gcc $^ -o $@
shm_read:shm_read.c
	gcc $^ -o $@
all:fifo_write fifo_read
fifo_write:fifo_write.c
	gcc $^ -o $@
fifo_read:fifo_read.c
	gcc $^ -o $@
pipe2:pipe2.c
	gcc $^ -o $@
pipe1:pipe1.c
	gcc $^ -o $@
