product_customer2:product_customer2.cpp
	g++ -std=c++11 $^ -o $@ -lpthread
product_customer:product_customer.cpp
	g++ -std=c++11 $^ -o $@ -lpthread
cond:cond.c
	gcc $^ -o $@ -lpthread
mutex:mutex.c
	gcc $^ -o $@ -lpthread
exit:exit.c
	gcc $^ -o $@ -lpthread
pthread1:pthread1.c
	gcc $^ -o $@ -lpthread
